### ISSUE TITLE
PowerShell with imported `CompletionPredictor` crashes on `git diff` command

### ISSUE THREAD

**Issue by kborowinski** [PowerShell/CompletionPredictor#22]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the latest version
- [X] Search the existing issues.

### Steps to reproduce

Environment:
1. Latest daily `PowerShell Core 7.4.0.preview-2` build
2. Latest `CompletionPredictor` module build *([with git completion support](https://github.com/PowerShell/CompletionPredictor/pull/21))*
3. `PSReadLine 2.3.0-beta0`
4. PowerShell profile:
```powershell
Import-Module -Name 'CompletionPredictor'

Set-PSReadLineOption -HistoryNoDuplicates
Set-PSReadLineOption -PredictionSource 'HistoryAndPlugin'

Set-PSReadlineKeyHandler -Key UpArrow -Function HistorySearchBackward
Set-PSReadlineKeyHandler -Key DownArrow -Function HistorySearchForward

$Parameters = @{
	Key			= 'RightArrow'
	BriefDescription	= 'ForwardCharAndAcceptNextSuggestionWord'
	ScriptBlock		= {
		param($key, $arg)
		$line = $null
		$cursor = $null
		[Microsoft.PowerShell.PSConsoleReadLine]::GetBufferState([Ref]$line, [Ref]$cursor)
		if ($cursor -lt $line.Length) {
			[Microsoft.PowerShell.PSConsoleReadLine]::ForwardChar($key, $arg)
		} else {
			[Microsoft.PowerShell.PSConsoleReadLine]::AcceptNextSuggestionWord($key, $arg)
		}
	}
}
Set-PSReadlineKeyHandler @Parameters

```

Steps:
```powershell
mkdir test
cd .\test\
git init
mkdir empty
git diff
```

### Expected behavior

```console
git diff should not crash PowerShell session
```

### Actual behavior

```console
PowerShell session crashes
```

### Error details

```console
N/A
```

### Environment data

```PowerShell
Name                           Value
----                           -----
PSVersion                      7.4.0-preview.2
PSEdition                      Core
GitCommitId                    7.4.0-preview.2-35-g78f1406fd2fed68aa6348df565b6824f8c187ef9
OS                             Microsoft Windows 10.0.19045
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Version

0.1.0

### Visuals

![crash](https://user-images.githubusercontent.com/16168755/230733969-f37011aa-e740-4716-a0b0-eb8ee1d4c84d.jpg)

**Comment by daxian-dbw** [comment]
@kborowinski Thank you for dogfooding the git handler changes!
I just merged some fixes (#23) for issues I found while using the module, and I think this issue was also resolved by that PR. Can you please build and give it a try? Thanks!

**Comment by kborowinski** [comment]
@daxian-dbw Yep, PR #23 fixed this issue. Thanks!

**Comment by daxian-dbw** [comment]
Thanks for verifying it! I appreciate it.
